// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndrxafxoguiquknatzki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kcnhhZnhvZ3VpcXVrbmF0emtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MDQ5MzUsImV4cCI6MjA2NzE4MDkzNX0.Q97NZNNikkHVQGENC3lXIUjua9l35VFC8CWPhfpwmO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});